loop_performance: loop_performance.c
	gcc -O2 -o $@ $^
loop_performance_o3: loop_performance.c
	gcc -O3 -o $@ $^
loop_fusion: loop_fusion.c
	gcc -O2 -o $@ $^
loop_reversal: loop_reversal.c
	gcc -O2 -o $@ $^
loop_peeling: loop_peeling.c
	gcc -O2 -o $@ $^
